export type HomeCopy = {
  eyebrow:string; title:string; intro:string; heroQuote:string; heroQuoteSource:string; ctaJoin:string; ctaUnderstand:string;
  realityEyebrow:string; realityTitle:string; realityLead:string; realityItems:string[]; bridge:string;
  movementTitle:string; movementBody:string; movementCards:Array<{title:string;body:string}>;
  edebatteTitle:string; edebatteBody:string; edebatteCta:string; voxyTitle:string; voxyBody:string; voxyQuote:string;
  transparencyTitle:string; transparencyBody:string; transparencyEyebrow:string; transparencyItems:string[];
  questionsTitle:string; questionsBody:string; questionsEyebrow:string; questionsCta:string; questions:string[];
  joinTitle:string; joinBody:string; membershipEyebrow:string; contactLabel:string; person:string; organisation:string;
  firstName:string; lastName:string; birthDate:string; organisationName:string; email:string; city:string; country:string;
  countryPlaceholder:string; privacy:string; newsletter:string; submit:string; submitting:string;
  supportTitle:string; supportBody:string; supportCta:string;
  formMissing:string; formSuccess:string; formFailed:string;
};

export const HOME_COPY_DE: HomeCopy = {
  eyebrow:"Eine internationale Mitgliederbewegung", title:"Willkommen Nachbar.",
  intro:"Wir kennen uns wahrscheinlich nicht. Trotzdem treffen wir jeden Tag Entscheidungen, die unser gemeinsames Leben beeinflussen. Vielleicht wird es Zeit, dass wir anfangen, sie gemeinsam besser zu verstehen.",
  heroQuote:"Vielleicht braucht es nicht noch eine Partei. Vielleicht braucht es endlich ein besseres Verfahren.", heroQuoteSource:"VoiceOpenGov · Entwurf einer Bewegung", ctaJoin:"Mitglied werden", ctaUnderstand:"Erst verstehen",
  realityEyebrow:"Realitätscheck", realityTitle:"Es läuft einiges schief. Das ist keine gewagte These.", realityLead:"Vertrauen sinkt, Diskussionen werden lauter, Informationen werden mehr und Orientierung wird weniger. Vielleicht fehlt uns keine weitere Meinung. Vielleicht fehlt uns ein besseres Verfahren.",
  realityItems:["Entscheidungen sind oft kaum nachvollziehbar.","Interessen und Verantwortung bleiben unsichtbar.","Menschen dürfen wählen, aber zu selten wirklich mitgestalten.","Fehler werden verteidigt, statt gemeinsam daraus zu lernen."],
  bridge:"VoiceOpenGov will nicht noch lauter werden. Wir wollen besser verstehen, fairer abwägen und Verantwortung sichtbar machen.",
  movementTitle:"Nicht noch eine fertige Wahrheit. Eine Bewegung, die offen arbeitet.", movementBody:"VoiceOpenGov bringt Menschen zusammen, die Politik und Gesellschaft nicht nur kritisieren, sondern nachvollziehbarer, souveräner und lernfähiger gestalten wollen.",
  movementCards:[{title:"Verstehen",body:"Quellen, Zusammenhänge und Zielkonflikte werden sichtbar, bevor bewertet wird."},{title:"Mitgestalten",body:"Mitglieder entwickeln Charta, Themen und regionale Arbeitsräume gemeinsam weiter."},{title:"Verantworten",body:"Entscheidungen, Finanzierung, Interessen und Kursänderungen bleiben prüfbar."}],
  edebatteTitle:"eDebatte ist das Instrument. Dort arbeitet die Bewegung.", edebatteBody:"Aus Quellen werden keine schnellen Parolen, sondern nachvollziehbare Claims, Alternativen, Beteiligung, Mehrheitsbilder, Minderheitenvoten und Wirkung. Der Reasoning Graph zeigt, wie aus Information eine Schlussfolgerung entsteht.", edebatteCta:"eDebatte öffnen",
  voxyTitle:"Voxy begleitet. Voxy entscheidet nicht.", voxyBody:"Voxy erklärt Charta, Mitgliedschaft und offene Fragen. In eDebatte strukturiert sie Beiträge, verbindet Quellen, erkennt Widersprüche und macht Unsicherheit sichtbar.", voxyQuote:"Du musst uns nicht glauben. Du sollst prüfen können, wie wir zu unseren Aussagen kommen.",
  transparencyTitle:"Wir verlangen nichts, was wir nicht selbst tun.", transparencyBody:"Transparenz ist kein Unterpunkt. Sie ist das Betriebssystem von VoiceOpenGov, eDebatte und Vote4Gov.", transparencyEyebrow:"Transparenzversprechen",
  transparencyItems:["Finanzierung und Abhängigkeiten","Entscheidungen und Verantwortlichkeiten","Mitgliederentwicklung und Governance","Quellen, Änderungen und offene Fehler","KI-Einsatz und Interessenkonflikte","Wirkung, Zweifel und Kurskorrekturen"],
  questionsTitle:"50 große Fragen. Keine 50 fertigen Antworten.", questionsBody:"Unsere ersten öffentlichen Räume beginnen nicht mit Parteischubladen, sondern mit den wichtigsten Zielkonflikten unserer Zeit.", questionsEyebrow:"Öffentliche Räume", questionsCta:"Alle 50 öffentlichen Fragen ansehen →",
  questions:["Wann ist eine politische Entscheidung wirklich legitim?","Wie schützen wir Freiheit und Sicherheit zugleich?","Wie nutzen wir KI so, dass sie Menschen stärkt?","Wie sichern wir Wohlstand und unsere Lebensgrundlagen?","Wie verbinden wir nationale Souveränität und internationale Verantwortung?","Wie lernen Gesellschaften sichtbar aus Fehlern?"],
  joinTitle:"Werde Nachbar.", joinBody:"Die Mitgliedschaft ist kostenfrei. Ein freiwilliger Beitrag hilft uns schneller zu wachsen, kauft aber niemals mehr Stimme oder Einfluss.", membershipEyebrow:"Mitgliedschaft", contactLabel:"Kontakt", person:"Person", organisation:"Organisation", firstName:"Vorname", lastName:"Nachname", birthDate:"Geburtsdatum", organisationName:"Organisation", email:"E-Mail", city:"Ort", country:"Land", countryPlaceholder:"Bitte wählen", privacy:"Ich akzeptiere die Datenschutzhinweise und das Double-Opt-In-Verfahren.", newsletter:"Ich möchte Updates zu VoiceOpenGov erhalten.", submit:"Kostenfrei Mitglied werden", submitting:"Wird eingetragen …",
  supportTitle:"Bewegung ermöglichen, ohne Einfluss zu verkaufen.", supportBody:"Mitgliedschaft und Finanzierung bleiben getrennt. Wer mehr gibt, erhält nicht mehr politische Gewichtung.", supportCta:"Freiwillig unterstützen",
  formMissing:"Bitte E-Mail, Ort und Datenschutz bestätigen.", formSuccess:"Fast geschafft. Bitte bestätige jetzt die E-Mail.", formFailed:"Das hat noch nicht funktioniert. Bitte versuche es erneut."
};

export const HOME_COPY_EN: HomeCopy = {
  eyebrow:"An international membership movement", title:"Welcome, neighbour.", intro:"We probably do not know each other. Yet every day we make decisions that affect our shared lives. Perhaps it is time we started understanding them better together.", heroQuote:"Perhaps we do not need another party. Perhaps we finally need a better process.", heroQuoteSource:"VoiceOpenGov · A movement in the making", ctaJoin:"Become a member", ctaUnderstand:"Understand first",
  realityEyebrow:"Reality check", realityTitle:"A lot is going wrong. That is hardly a radical claim.", realityLead:"Trust is declining, debates are getting louder, information is increasing and orientation is disappearing. Perhaps we do not need another opinion. Perhaps we need a better process.", realityItems:["Decisions are often hard to trace.","Interests and responsibility remain hidden.","People may vote, but rarely shape decisions continuously.","Mistakes are defended instead of becoming shared learning."], bridge:"VoiceOpenGov does not aim to become louder. We aim to understand better, weigh fairly and make responsibility visible.",
  movementTitle:"Not another finished truth. A movement that works in the open.", movementBody:"VoiceOpenGov connects people who want to do more than criticise politics and society: they want to make both more transparent, sovereign and capable of learning.", movementCards:[{title:"Understand",body:"Sources, connections and trade-offs become visible before judgement."},{title:"Shape",body:"Members develop the charter, topics and regional spaces together."},{title:"Take responsibility",body:"Decisions, funding, interests and changes remain auditable."}],
  edebatteTitle:"eDebatte is the instrument. It is where the movement works.", edebatteBody:"Sources do not become quick slogans, but traceable claims, alternatives, participation, majority pictures, minority views and measured effects. The reasoning graph shows how information becomes a conclusion.", edebatteCta:"Open eDebatte", voxyTitle:"Voxy assists. Voxy does not decide.", voxyBody:"Voxy explains the charter, membership and open questions. In eDebatte, she structures contributions, connects sources, detects contradictions and makes uncertainty visible.", voxyQuote:"You do not have to believe us. You should be able to inspect how we reached our conclusions.",
  transparencyTitle:"We demand nothing we are unwilling to do ourselves.", transparencyBody:"Transparency is not a subsection. It is the operating system of VoiceOpenGov, eDebatte and Vote4Gov.", transparencyEyebrow:"Transparency promise", transparencyItems:["Funding and dependencies","Decisions and responsibilities","Membership development and governance","Sources, changes and open mistakes","AI use and conflicts of interest","Impact, doubts and course corrections"],
  questionsTitle:"50 major questions. Not 50 finished answers.", questionsBody:"Our first public spaces begin with the defining trade-offs of our time, not party categories.", questionsEyebrow:"Public spaces", questionsCta:"View all 50 public questions →", questions:["When is a political decision truly legitimate?","How do we protect freedom and security at the same time?","How do we use AI to strengthen people?","How do we protect prosperity and the foundations of life?","How do we connect national sovereignty and international responsibility?","How do societies visibly learn from mistakes?"],
  joinTitle:"Become a neighbour.", joinBody:"Membership is free. A voluntary contribution helps us grow faster, but never buys more voice or influence.", membershipEyebrow:"Membership", contactLabel:"Contact", person:"Person", organisation:"Organisation", firstName:"First name", lastName:"Last name", birthDate:"Date of birth", organisationName:"Organisation", email:"Email", city:"City", country:"Country", countryPlaceholder:"Please choose", privacy:"I accept the privacy notice and double opt-in process.", newsletter:"I would like updates about VoiceOpenGov.", submit:"Join for free", submitting:"Joining …", supportTitle:"Enable the movement without selling influence.", supportBody:"Membership and funding remain separate. Giving more never creates more political weight.", supportCta:"Support voluntarily",
  formMissing:"Please provide email, city and privacy consent.", formSuccess:"Almost there. Please confirm your email.", formFailed:"That did not work yet. Please try again."
};
