import type { SupportedLocale } from "@/config/locales";

type EcosystemCopy = {
  eyebrow:string; title:string; body:string; footerLine:string;
  items:{ edebatte:{role:string;description:string}; voiceopengov:{role:string;description:string}; vote4gov:{role:string;description:string}; voxy:{role:string;description:string} };
};

const EN: EcosystemCopy = {
  eyebrow:"One ecosystem. Four clearly separated roles.", title:"Shared principles. Independent responsibilities.", body:"VoiceOpenGov uses eDebatte. It does not own eDebatte. Vote4Gov explores how society can evolve. Voxy connects the layers without making decisions.", footerLine:"Transparency is our shared operating system.",
  items:{edebatte:{role:"Open infrastructure",description:"For traceable insight, orientation and participation — open to citizens, municipalities, businesses, associations, parties, academia, media and NGOs."},voiceopengov:{role:"International membership movement",description:"People organise across borders and take shared responsibility."},vote4gov:{role:"Civic think tank",description:"Explores how democratic participation can be developed responsibly in the digital age."},voxy:{role:"Connecting guide",description:"Explains, structures and translates. Voxy helps people understand. Voxy does not decide."}}
};

const COPY: Partial<Record<SupportedLocale, EcosystemCopy>> = {
  de:{eyebrow:"Ein Ökosystem. Vier klar getrennte Rollen.",title:"Gemeinsame Haltung. Eigenständige Aufgaben.",body:"VoiceOpenGov nutzt eDebatte. Es besitzt eDebatte nicht. Vote4Gov denkt gesellschaftliche Entwicklung weiter. Voxy verbindet die Ebenen, ohne Entscheidungen zu treffen.",footerLine:"Transparenz ist unser gemeinsames Betriebssystem.",items:{edebatte:{role:"Offene Infrastruktur",description:"Für nachvollziehbare Erkenntnis, Orientierung und Beteiligung – offen für Bürger, Kommunen, Unternehmen, Vereine, Parteien, Wissenschaft, Medien und NGOs."},voiceopengov:{role:"Internationale Mitgliederbewegung",description:"Menschen organisieren sich über Grenzen hinweg und übernehmen gemeinsam Verantwortung."},vote4gov:{role:"Gesellschaftliche Denkwerkstatt",description:"Reflektiert, wie demokratische Mitbestimmung im digitalen Zeitalter verantwortungsvoll weiterentwickelt werden kann."},voxy:{role:"Verbindende Begleiterin",description:"Erklärt, strukturiert und übersetzt. Voxy hilft beim Verstehen. Voxy entscheidet nicht."}}},
  en:EN,
  fr:{eyebrow:"Un écosystème. Quatre rôles clairement séparés.",title:"Des principes communs. Des responsabilités indépendantes.",body:"VoiceOpenGov utilise eDebatte sans la posséder. Vote4Gov réfléchit à l’évolution de la société. Voxy relie les niveaux sans prendre de décisions.",footerLine:"La transparence est notre système d’exploitation commun.",items:{edebatte:{role:"Infrastructure ouverte",description:"Pour une compréhension, une orientation et une participation traçables — ouverte aux citoyens, communes, entreprises, associations, partis, universités, médias et ONG."},voiceopengov:{role:"Mouvement international de membres",description:"Des personnes s’organisent au-delà des frontières et assument une responsabilité commune."},vote4gov:{role:"Laboratoire d’idées citoyen",description:"Explore comment développer la participation démocratique de manière responsable à l’ère numérique."},voxy:{role:"Guide de liaison",description:"Explique, structure et traduit. Voxy aide à comprendre. Voxy ne décide pas."}}},
  es:{eyebrow:"Un ecosistema. Cuatro funciones claramente separadas.",title:"Principios compartidos. Responsabilidades independientes.",body:"VoiceOpenGov utiliza eDebatte, pero no es su propietaria. Vote4Gov explora cómo puede evolucionar la sociedad. Voxy conecta los niveles sin tomar decisiones.",footerLine:"La transparencia es nuestro sistema operativo común.",items:{edebatte:{role:"Infraestructura abierta",description:"Para conocimiento, orientación y participación trazables — abierta a ciudadanía, municipios, empresas, asociaciones, partidos, academia, medios y ONG."},voiceopengov:{role:"Movimiento internacional de miembros",description:"Las personas se organizan más allá de las fronteras y asumen responsabilidad compartida."},vote4gov:{role:"Laboratorio cívico de ideas",description:"Explora cómo desarrollar responsablemente la participación democrática en la era digital."},voxy:{role:"Guía de conexión",description:"Explica, estructura y traduce. Voxy ayuda a comprender. Voxy no decide."}}},
  tr:{eyebrow:"Tek ekosistem. Açıkça ayrılmış dört rol.",title:"Ortak ilkeler. Bağımsız sorumluluklar.",body:"VoiceOpenGov eDebatte’yi kullanır; ona sahip değildir. Vote4Gov toplumun nasıl gelişebileceğini araştırır. Voxy karar vermeden katmanları birbirine bağlar.",footerLine:"Şeffaflık ortak işletim sistemimizdir.",items:{edebatte:{role:"Açık altyapı",description:"İzlenebilir bilgi, yönelim ve katılım için — vatandaşlara, belediyelere, işletmelere, derneklere, partilere, akademiye, medyaya ve STK’lara açık."},voiceopengov:{role:"Uluslararası üyelik hareketi",description:"İnsanlar sınırlar ötesinde örgütlenir ve ortak sorumluluk üstlenir."},vote4gov:{role:"Toplumsal düşünce atölyesi",description:"Dijital çağda demokratik katılımın sorumlu biçimde nasıl geliştirilebileceğini araştırır."},voxy:{role:"Bağlayıcı rehber",description:"Açıklar, yapılandırır ve çevirir. Voxy anlamaya yardımcı olur. Voxy karar vermez."}}},
  ar:{eyebrow:"منظومة واحدة. أربعة أدوار منفصلة بوضوح.",title:"مبادئ مشتركة. مسؤوليات مستقلة.",body:"تستخدم VoiceOpenGov منصة eDebatte ولا تملكها. تستكشف Vote4Gov تطور المجتمع. وتربط Voxy المستويات من دون اتخاذ القرارات.",footerLine:"الشفافية هي نظام التشغيل المشترك بيننا.",items:{edebatte:{role:"بنية تحتية مفتوحة",description:"للمعرفة القابلة للتتبع والتوجيه والمشاركة — ومفتوحة للمواطنين والبلديات والشركات والجمعيات والأحزاب والأوساط الأكاديمية والإعلام والمنظمات غير الحكومية."},voiceopengov:{role:"حركة عضوية دولية",description:"ينظم الناس أنفسهم عبر الحدود ويتحملون مسؤولية مشتركة."},vote4gov:{role:"مختبر أفكار مجتمعي",description:"يستكشف كيفية تطوير المشاركة الديمقراطية بمسؤولية في العصر الرقمي."},voxy:{role:"دليل رابط",description:"تشرح وتنظم وتترجم. تساعد Voxy على الفهم ولا تتخذ القرارات."}}}
};

export function getFooterEcosystemStrings(locale: SupportedLocale): EcosystemCopy {
  return COPY[locale] ?? EN;
}
